INSERT INTO BMI{termin} (
    abweisen_check_befund_check_beschreibung_extern,
    abweisen_check_befund_check_beschreibung_kurz,
    abweisen_check_befund_check_details,
    abweisen_check_befund_check_gruppe,
    abweisen_check_befund_check_name,
    anwendungs_id,
    befoerderungs_datum,
    blz,
    comment,
    datei,
    datei_id,
    dateiname,
    empfangszeit,
    erstellt,
    externe_referenz,
    id1,
    id2,
    import_anwendungs_id,
    import_befoerderungs_datum,
    import_blz,
    import_datei_id,
    import_dateiname,
    import_empfangszeit,
    import_externe_referenz,
    import_found,
    import_melder_id,
    import_melder_id_art,
    import_meldetermin,
    institutstyp,
    last_updated,
    melder_id,
    melder_id_art,
    meldetermin,
    ok,
    rejected_import_found,
    termin,
    typ
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT DO UPDATE SET
    abweisen_check_befund_check_beschreibung_extern = excluded.abweisen_check_befund_check_beschreibung_extern,
    abweisen_check_befund_check_beschreibung_kurz = excluded.abweisen_check_befund_check_beschreibung_kurz,
    abweisen_check_befund_check_details = excluded.abweisen_check_befund_check_details,
    abweisen_check_befund_check_gruppe = excluded.abweisen_check_befund_check_gruppe,
    abweisen_check_befund_check_name = excluded.abweisen_check_befund_check_name,
    anwendungs_id = excluded.anwendungs_id,
    befoerderungs_datum = excluded.befoerderungs_datum,
    blz = excluded.blz,
    datei = excluded.datei,
    datei_id = excluded.datei_id,
    dateiname = excluded.dateiname,
    empfangszeit = excluded.empfangszeit,
    erstellt = excluded.erstellt,
    externe_referenz = excluded.externe_referenz,
    id1 = excluded.id1,
    id2 = excluded.id2,
    import_anwendungs_id = excluded.import_anwendungs_id,
    import_befoerderungs_datum = excluded.import_befoerderungs_datum,
    import_blz = excluded.import_blz,
    import_datei_id = excluded.import_datei_id,
    import_dateiname = excluded.import_dateiname,
    import_empfangszeit = excluded.import_empfangszeit,
    import_externe_referenz = excluded.import_externe_referenz,
    import_found = excluded.import_found,
    import_melder_id = excluded.import_melder_id,
    import_melder_id_art = excluded.import_melder_id_art,
    import_meldetermin = excluded.import_meldetermin,
    institutstyp = excluded.institutstyp,
    last_updated = excluded.last_updated,
    melder_id = excluded.melder_id,
    melder_id_art = excluded.melder_id_art,
    meldetermin = excluded.meldetermin,
    rejected_import_found = excluded.rejected_import_found,
    termin = excluded.termin,
    typ = excluded.typ