INSERT INTO BMI{termin} (
    abweisen_check_befund_check_beschreibung_extern,
    abweisen_check_befund_check_beschreibung_kurz,
    abweisen_check_befund_check_details,
    abweisen_check_befund_check_gruppe,
    abweisen_check_befund_check_name,
    anwendungs_id,
    befoerderungs_datum,
    blz,
    comment,
    datei,
    datei_id,
    dateiname,
    empfangszeit,
    erstellt,
    externe_referenz,
    id1,
    id2,
    import_anwendungs_id,
    import_befoerderungs_datum,
    import_blz,
    import_datei_id,
    import_dateiname,
    import_empfangszeit,
    import_externe_referenz,
    import_found,
    import_melder_id,
    import_melder_id_art,
    import_meldetermin,
    institutstyp,
    last_updated,
    melder_id,
    melder_id_art,
    meldetermin,
    ok,
    rejected_import_found,
    termin,
    typ
)
VALUES (
    'hghghg', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, '', '', '', '', '', '', '', '', 0, 0, '', ''
)
ON CONFLICT DO UPDATE SET
    abweisen_check_befund_check_beschreibung_extern = excluded.abweisen_check_befund_check_beschreibung_extern,
    abweisen_check_befund_check_beschreibung_kurz = excluded.abweisen_check_befund_check_beschreibung_kurz,
    abweisen_check_befund_check_details = excluded.abweisen_check_befund_check_details,
    abweisen_check_befund_check_gruppe = excluded.abweisen_check_befund_check_gruppe,
    abweisen_check_befund_check_name = excluded.abweisen_check_befund_check_name,
    anwendungs_id = excluded.anwendungs_id,
    befoerderungs_datum = excluded.befoerderungs_datum,
    blz = excluded.blz