 SELECT [meldetermin]
          ,[melder_id_art]
          ,[melder_id]
          ,[import_anwendungs_id]
          ,[import_blz]
          ,[import_befoerderungs_datum]
          ,[import_externe_referenz]
          ,[import_datei_id]
          ,[import_empfangszeit]
          ,[import_dateiname]
          ,[abweisen_check_befund_check_name]
          ,[abweisen_check_befund_check_gruppe]
          ,[abweisen_check_befund_check_beschreibung_kurz]
          ,[abweisen_check_befund_check_beschreibung_extern]
          ,[abweisen_check_befund_check_details]
          ,[import_meldetermin]
          ,[import_melder_id_art]
          ,[import_melder_id]
      FROM [REPORTING].[dbo].[wpi-importe-abgewiesen-flat]
      WHERE import_befoerderungs_datum > '{IMPORT_CUT_DATE}'